-- DDL generated by Postico 1.5.20

CREATE TABLE todos (
    id SERIAL PRIMARY KEY,
    text character varying(255) NOT NULL UNIQUE,
    priority integer NOT NULL DEFAULT 1,
    "isCompleted" boolean NOT NULL DEFAULT false,
    "createdAt" timestamp with time zone NOT NULL,
    "updatedAt" timestamp with time zone NOT NULL,
    "createTime" timestamp with time zone DEFAULT now(),
    "completedTime" timestamp with time zone
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX todos_pkey ON todos(id int4_ops);
CREATE UNIQUE INDEX todos_text_key ON todos(text text_ops);
